import Head from 'next/head';
import { Heading, Carousel, Breadcrumbs, Description, InfoBlock } from '@/components';

const headingProps = {
  title: 'Toyota Land Cruiser, 2020',
  subtitle: 'Южно-Сахалинск',
  statistics: {
    views: '344 (+11 сегодня)',
    favorites: '87 (+2 сегодня)'
  }
};

const descriptionProps = {
  title: '',
  list: [{
    name: '',
    value: ''
  },
  {
    name: '',
    value: ''
  }]
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Home Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Breadcrumbs></Breadcrumbs>
        <Heading headingProps={headingProps} />
        <Carousel></Carousel>
        <InfoBlock></InfoBlock>
        <Description descriptionProps={descriptionProps}/>
      </main>
    </>
  )
}
