import Head from 'next/head';
import { Golos_Text } from 'next/font/google';
import { Heading, Carousel, Breadcrumbs, Description, InfoBlock } from '@/components';
import { headingData, descriptionData, carouselData, breadcrumbsData, infoData } from './data';

const golos = Golos_Text({subsets: ['latin', 'cyrillic']});

export default function Home() {

  return (
    <>
      <Head>
        <title>Home Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={golos.className}>
        <Breadcrumbs breadcrumbsData={breadcrumbsData}></Breadcrumbs>
        <Heading headingData={headingData} />
        <Carousel carouselData={carouselData}></Carousel>
        <InfoBlock infoData={infoData}></InfoBlock>
        <Description descriptionProps={descriptionData}/>
      </main>
    </>
  )
}
