import Head from 'next/head';
import { Golos_Text } from 'next/font/google';
import { Heading, Gallery, Breadcrumbs, Description, InfoBlock } from '@/components';
import { headingData, descriptionData, galleryData, breadcrumbsData, infoData } from '../components/data';
import styled from '@emotion/styled';

const Container = styled.div`
  position: relative;
`;

const golos = Golos_Text({subsets: ['latin', 'cyrillic'], display: 'swap'});

export default function Home() {

  return (
    <>
      <Head>
        <title>Home Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={golos.className}>
        <Breadcrumbs breadcrumbsData={breadcrumbsData}></Breadcrumbs>
        <Container>
          <InfoBlock infoData={infoData}></InfoBlock>
          <Heading headingData={headingData} />
          <Gallery galleryData={galleryData}></Gallery>
          <Description descriptionProps={descriptionData}/>
        </Container>
      </main>
    </>
  )
}
